### ISSUE TITLE
Revisit transaction handling 

### ISSUE THREAD

**Issue by soccermax** [cap-js-community/event-queue#13]
- in case of `commitOnEventLevel=false` transaction might be rolled back even the status for certain events in the same batch is done
- possible solution could be to extend the event configuration for a transaction mode
  -  commitOnEventLevel --> write status after every `processEvent`
  -  commitChunk --> commit status at the end --> if one event is reported as erroneous set all events on error
  - independedOfProcessingStatus --> commit status at the end as reported by `processEvent` --> all events in the chunk get the same transaction

**Comment by soccermax** [comment]
check also status status exceeded is being rolled back --> not only error

**Comment by soccermax** [comment]
add additional flag:
- atomic status commit

```yaml
  - type: Fiori
    subType: Task
    impl: ./test/asset/EventQueueTest
    load: 40
    parallelEventProcessing: 5
    runAutomatically: true
    processAfterCommit: true
    transactionHandling:
      commitOnEventLevel: false
      atomicStatusHandling: false
``` 

--> to address the issue the new section `transactionHandling` could be added

**Comment by soccermax** [comment]
```yaml
  - type: Fiori
    subType: Task
    impl: ./test/asset/EventQueueTest
    load: 40
    parallelEventProcessing: 5
    runAutomatically: true
    processAfterCommit: true
    transactionMode: commitOnEventLevel || http
``` 

--> new flag is transactionMode
