### ISSUE TITLE
Started seeing error 'No implementation found in the provided configuration file' today

### ISSUE THREAD

**Issue by js1972** [cap-js-community/event-queue#88]
I haven't tested for a couple of days and now when I deploy my CAP app with the event-queue I get the following error and no events run.

<img width="1168" alt="image" src="https://github.com/cap-js-community/event-queue/assets/1317161/8c7f0322-cad6-41d1-b8c7-a0078280a4fd">

Here's my config file - which has not changed:
```
periodicEvents:
  - type: DataSync
    subType: DB
    impl: ./srv/EventQueueSyncAdoptionTrackerData
    load: 10
    interval: 86400
```

<img width="304" alt="image" src="https://github.com/cap-js-community/event-queue/assets/1317161/e18e5f43-7b63-4487-958f-840b8359c1fa">

Maybe related to the 0.3.0 release, though I don't see anything that stands out in the change log.
